[package]
name = "serde_bucket"
version = "0.1.0"
edition = "2021"

[features]
#alloc = ["serde/alloc"]
#default = ["alloc"]
error = []

[dependencies]
serde = { version = "1.0.152"}

[dev-dependencies]
serde_json = "1.0.96"
serde = { features = ["derive"] }